server:
  port: 9000

spring:
  application:
    name: "loans"
  profiles:
    active: "qa"
  datasource:
    url: "jdbc:postgresql://localhost:5434/loansdb"
    username: "gabriel"
    password: "1234"
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: "optional:configserver:http://localhost:8071"
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"