services:

  accountsdb:
    image: postgres:16.2
    container_name: accountsdb
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U gabriel -d accountsdb
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    environment:
      POSTGRES_USER: "gabriel"
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: "accountsdb"
    extends:
      file: common-config.yml
      service: network-deploy-service

  cardsdb:
    image: postgres:16.2
    container_name: cardsdb
    ports:
      - "5433:5432"
    healthcheck:
      test: pg_isready -U gabriel -d cardsdb
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    environment:
      POSTGRES_USER: "gabriel"
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: "cardsdb"
    extends:
      file: common-config.yml
      service: network-deploy-service

  loansdb:
    image: postgres:16.2
    container_name: loansdb
    ports:
      - "5434:5432"
    healthcheck:
      test: pg_isready -U gabriel -d loansdb
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    environment:
      POSTGRES_USER: "gabriel"
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: "loansdb"
    extends:
      file: common-config.yml
      service: network-deploy-service

  rabbit:
    image: rabbitmq:3.13-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    extends:
      file: common-config.yml
      service: network-deploy-service

  configserver:
    image: "gabrielleone/configserver:v4"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    depends_on:
      rabbit:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://configserver:8071/actuator/health/readiness"]
      interval: 10s
      timeout: 2s
      retries: 10
    extends:
      file: common-config.yml
      service: microservice-base-config

  accounts:
    image: "gabrielleone/accounts:v3"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    depends_on:
      configserver:
        condition: service_healthy
      accountsdb:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://accountsdb:5432/accountsdb"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  cards:
    image: "gabrielleone/cards:v3"
    container_name: cards-ms
    ports:
      - "8090:8090"
    restart: always
    depends_on:
      configserver:
        condition: service_healthy
      cardsdb:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "cards"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://cardsdb:5432/cardsdb"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  loans:
    image: "gabrielleone/loans:v3"
    container_name: loans-ms
    ports:
      - "9000:9000"
    depends_on:
      configserver:
        condition: service_healthy
      loansdb:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "loans"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://loansdb:5432/loansdb"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

networks:
  eazybank:
    driver: "bridge"